Repository mesosphere/mindthegap, pull requests merged in 2022-09, with the labels that each got.

#174 fix!: Remove unnecessary gzip compression of bundles by default
  .gitignore
  README.md
  archive/archive_test.go
  cmd/mindthegap/create/create.go
  cmd/mindthegap/create/helmbundle/helm_bundle.go
  cmd/mindthegap/create/imagebundle/image_bundle.go
Labels: fix, breaking

#183 feat: support globs for image and helm bundles
  cmd/mindthegap/importcmd/imagebundle/image_bundle.go
  cmd/mindthegap/push/helmbundle/helm_bundle.go
  cmd/mindthegap/push/imagebundle/image_bundle.go
  cmd/mindthegap/serve/helmbundle/helm_bundle.go
  cmd/mindthegap/serve/imagebundle/image_bundle.go
  cmd/mindthegap/utils/glob.go
  cmd/mindthegap/utils/glob_test.go
Labels: feature

#185 fix: Ensure that image IDs do not change on import
  cmd/mindthegap/importcmd/imagebundle/image_bundle.go
Labels: fix

#191 fix: Ensure file permissions are preserved when copying files
  cmd/mindthegap/utils/copy_file.go
Labels: fix

#192 test: Add e2e test for import image-bundle
  go.mod
  go.sum
  make/go.mk
  test/e2e/helmbundle/create_bundle_test.go
  test/e2e/helmbundle/helm_bundle_suite_test.go
  test/e2e/helmbundle/helpers/helpers.go
  test/e2e/helmbundle/push_bundle_test.go
  test/e2e/helmbundle/serve_bundle_test.go
  test/e2e/imagebundle/helpers/docker.go
  test/e2e/imagebundle/helpers/helpers.go
  test/e2e/imagebundle/imagebundle_suite_test.go
  test/e2e/imagebundle/import_bundle_test.go
  test/e2e/imagebundle/testdata/import-bundle.yaml
Labels: fix

#195 fix: Properly handle friendly image names
  README.md
  config/images_config.go
  config/images_config_test.go
  config/testdata/images/multiple_registries_with_multiple_images_with_multiple_tags_in_plain_text_file.txt
  test/e2e/imagebundle/import_bundle_test.go
  test/e2e/imagebundle/testdata/import-bundle.txt
Labels: fix

#198 feat: Add Docker image
  .envrc
  .github/workflows/checks-macos.yml
  .goreleaser.yml
  .tool-versions
  Dockerfile
  make/docker.mk
  make/skopeo.mk
Labels: feature

#206 fix: Correctly identify ECR registries
  docker/ecr/registry.go
  docker/ecr/registry_test.go
Labels: bug, fix

#207 test: Update sha for import bundle check
  test/e2e/imagebundle/import_bundle_test.go
Labels: bug
